package com.grp2.foodorderingsystem;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.ListView;

public class InsertSceneController implements Initializable {
	@FXML
	private ChoiceBox<String> fsComboBox;
	
	@FXML
	private ChoiceBox<Integer> qComboBox;
	
	@FXML
	private ListView<String> fsListView;
	
	private String[] food = {"pizza","sushi","ramen"};
	
	private Integer[] qFood = {1,2,3,4,5,6,7,8,9};
	// Event Listener on Button.onAction
	
	@FXML
	public void btnAdd(ActionEvent event) {
		// TODO Autogenerated
		String selectedFood = fsComboBox.getValue();
//		FoodArray selectedFood = new FoodArray(fsComboBox.getValue());
		String[][] foodTwoD = new String[3][3];	
		ArrayList<String> food = new ArrayList<String>();
		int x=0;
		int y=0;
		foodTwoD[x][y] = selectedFood;
		food.add(selectedFood);
		
		for(int i =0;i<foodTwoD.length;i++) {
			System.out.println();
			for(int j=0;j<foodTwoD[i].length;j++) {
				System.out.print(foodTwoD[i][j]+" ");
			}
		}
		
		fsListView.getItems().addAll(selectedFood);
	}
	
	@FXML
	public void btnConfirmOrder(ActionEvent event) {
		
		System.out.println("Confirmed!");
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		fsComboBox.getItems().addAll(food);
//		qComboBox.getItems().addAll(qFood);
	}
	
}
